apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nqc-backend
spec:
  ingressClassName: tailscale
  tls:
    - hosts: [nqc-backend]
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nqc-backend
                port:
                  number: 80
