apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: argocd
    namespace: argocd
    name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 10.2.0 # NOTE: v3.4.5
    valuesFile: values.yml
resources:
  - ./custom-resources/applications/root.yml
  - ./custom-resources/httproute/argocd-server.yml
