# NOTE: Source: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
crds:
  install: true

global:
  domain: argocd.tail689c1e.ts.net

configs:
  # NOTE: General Argo CD configuration. Any values you put under `.configs.cm` are passed to argocd-cm ConfigMap.
  # Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  cm:
    create: true
    kustomize.buildOptions: --enable-helm
    # NOTE: Create users
    accounts.youssef: apiKey, login
    accounts.ibrahim: apiKey, login

  rbac:
    create: true
    policy.csv: |
      g, youssef, role:admin
      g, ibrahim, role:admin

server:
  # WARN: Disable self-signed TLS certificate for ArgoCD server (use Gateway API instead)
  extraArgs:
    - --insecure
