apiVersion: v1
kind: ConfigMap
metadata:
  name: nuqc-backend
data:
  DATABASE_URL: sqlite:////var/lib/nuqc/db.sqlite
  DJANGO_DEBUG: "False"
  DJANGO_ENVIRONMENT: PROD
  DJANGO_ALLOWED_HOSTS: nuqc-backend,localhost,127.0.0.1
