apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nuqc-backend
spec:
  encryptedData:
    DJANGO_SECRET_KEY: AgCN11cH4xYJAtQxYvFnLfelKKSXNqktKovc1PS/jRjT8QeFB+wF7MoKAkbUu8b/U2rtGLiZMCZvmI2x1KwL0HxIRrGW1EL3iEy49rnyMSnoTjjpStzmPWbVjcc3hNhjOrpBEkDjZTDp0QSwd9FwIJJvEIqCO1OJ4nkMoMPM9S7r+kAOHooDs9qHk7gq16rrGhOTmYoNZ5Y8zAwyhXU9gjrvlKHFF5rJN4deP0ZJl14HsXh2B1o6ZXq8MfZCcYzImSYOXbxdVhAngY2Y7dLl9PC+epR4wRgIxK6XBueqmYixEVlquyxkA3ZsDKqpBxm/EsnfNEle8jdXAnx2m6PC3KhK4OQNjJrlzrHtEXD7ryf0VH1u0OqANi5P4YiuPpbx0A2zKXhmAQsPivtOdeWZnJ0T0ibxZnKLDunwz//G+TBjtTLcCKkvf35ZlamUmq0Jp/7lf5B7QrChpbfGVEz28IwOGr54Dj8gqvr1qLzzH9Ad3ia2rXNZM1yVaUuisnJWVIdA7sVH0oV1iS/me84G4YylGNjOMj8ssep358cf1Vgnhc7/FFDCzluPOnx3W/nuXzmXUuM7y70Kmn9HoUxrUcda/Xicad4zgJvI0zUkgpvfNiEfHnEl+hwDh6qQtoBHwKKlsYuhSW2cniNxkTYKB597KQGYBwnvm5glCh8OOTtra2CdeSkNxDz+KxchkhOT+IdG1Zo1guAHuwCAuWs3XUj9XuziWz9JHW6SoqjfNuwzWnki0HgXY8Zzf/PNoqAy69kcOg==
  template:
    metadata:
      name: nuqc-backend
