# NOTE: Ref: https://helmfile.readthedocs.io/en/latest/#configuration
repositories:
  - name: argo
    url: ghcr.io/argoproj/argo-helm
    oci: true

releases:
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: 10.2.0 # NOTE: ArgoCD v3.4.5
    values:
      - cluster/argocd/helm-values.yml
