apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: sealed-secrets
    name: sealed-secrets
    namespace: sealed-secrets
    repo: https://bitnami.github.io/sealed-secrets
    version: 2.19.1 # NOTE: v0.38.4
