apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  project: default
  source:
    repoURL: https://github.com/nile-quran-community/infra.git
    targetRevision: main
    path: cluster
    directory:
      include: appset.yml
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreatNamespace=true
      - ServerSideApply=true
