apiVersion: apps/v1
kind: Deployment
metadata:
  name: nqc-backend
  labels:
    app: nqc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nqc-backend
  template:
    metadata:
      labels:
        app: nqc-backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: nqc-backend
          image: ghcr.io/nile-quran-community/nile-quran-django:latest
          envFrom:
            - configMapRef:
                name: nqc-backend
            - secretRef:
                name: nqc-backend
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            timeoutSeconds: 10
            exec:
              command:
                - django-admin
                - check
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nqc-db
              mountPath: /var/lib/nqc
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nqc-db
          persistentVolumeClaim:
            claimName: nqc-db
