apiVersion: apps/v1
kind: Deployment
metadata:
  name: nqc-backend
  labels:
    app: nqc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nqc-backend
  template:
    metadata:
      labels:
        app: nqc-backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: nqc-backend
          image: ghcr.io/nile-quran-community/nile-quran-django:latest
          envFrom:
            - configMapRef:
                name: nqc-backend
            - secretRef:
                name: nqc-backend
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: nqc-db
              mountPath: /var/lib/nqc
          readinessProbe:
            timeoutSeconds: 10
            exec:
              command:
                - django-admin
                - check
      volumes:
        - name: nqc-db
          persistentVolumeClaim:
            claimName: nqc-db
