apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nqc-backend
spec:
  encryptedData:
    DJANGO_SECRET_KEY: AgCKY+IMtKPKbcCv9Zrz8BA4vWJjKCehMyQYS7kGV5r2x/hZRu0clHjuiDaP1yXJ+LDRZMaNLR6/nhV6YRx4LPQn14W8OMDO1GMKS5AK3Lx7O/ay83ijfhsid7spRLzxCsWbIgH8QVMy4XT9xFSyGBrbLOQh+jg3nnA+hQzivjabUDDmzTeMuHRpNrvgvTll+61tQI8YVK2nOBRqzzbnkXdyAF5zQCdVtGX6V65rqR/DM2vwcNHD/6dONSbfRm4sTxLAWVv1WHDYTZ470eV5A7x+2mbe/aR/3NYD1v0Dzzlxg7uIMlDkmmB7d+EcXPH2eMs1i1DmEt009kjHS1okQi4O9WyEwTlnIzeLj5pHrHgWkx1GnTbuKz5z1h2Jrpa9fwI96iT3enVg/GFijAM/wjaiXRp/Euz3eUc4jiz7XrtZu+3GOkyz0DAdWrv9LGtDcr582Mpj3fZg6Hb1AsRuXuUxIDH8onoDA10JZenFG8KhwaUWyVzOVpUezdU3YVLYDqUMLz+dhkTej9gtPpeo4FBi1zhWQ2L1B3+cmhKjmWfWx3zXd1bHhpaxSaJOdShwDwnw681+alkXM18E0bHj7RyaPJZhqx0fZZuP7KlcrCfVdOfYrh9YHueicEu02o2Wg3/YCtvmvBqSOkTn3AhXK6xe26s7L5qxtrmX3wwstmXLwxAkz3Cr6LCg+mvTp+khG6ueCqEjyIVp4iBjypM+nNJgKimKEKwR/PRyeApgBmmMlIRJgQONawgl5Up8zPFlCEzp0w==
  template:
    metadata:
      name: nqc-backend
