apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./custom-resources/backend/pvc.yml
  - ./custom-resources/backend/configmap.yml
  - ./custom-resources/backend/sealed-secret.yml
  - ./custom-resources/backend/deployment.yml
  - ./custom-resources/backend/service.yml
  - ./custom-resources/frontend/configmap.yml
  - ./custom-resources/frontend/deployment.yml
  - ./custom-resources/frontend/service.yml
  - ./custom-resources/filters/rate-limit.yml
  - ./custom-resources/httproute/frontend.yml
  - ./custom-resources/ingress/nqc-backend.yml
  - ./custom-resources/backend/backup-pvc.yml
  - ./custom-resources/backend/backup-cronjob.yml
images:
  - name: ghcr.io/nile-quran-community/nile-quran-nextjs
    newTag: 2.11.1@sha256:a6617841ff31610d929e64d82fbdce5b50664e563775148335510b4a23f418c2
  - name: ghcr.io/nile-quran-community/nile-quran-django
    newTag: 1.7.1@sha256:f58500858983412327eca539393dc4f6d6ebc9bfb7496d0cc07f98613e52afca
