apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./custom-resources/backend/pvc.yml
  - ./custom-resources/backend/configmap.yml
  - ./custom-resources/backend/sealed-secret.yml
  - ./custom-resources/backend/deployment.yml
  - ./custom-resources/backend/service.yml
  - ./custom-resources/frontend/configmap.yml
  - ./custom-resources/frontend/deployment.yml
  - ./custom-resources/frontend/service.yml
  - ./custom-resources/filters/rate-limit.yml
  - ./custom-resources/httproute/frontend.yml
  - ./custom-resources/ingress/nqc-backend.yml
  - ./custom-resources/backend/backup-pvc.yml
  - ./custom-resources/backend/backup-cronjob.yml
images:
  - name: ghcr.io/nile-quran-community/nile-quran-nextjs
    newTag: 2.10.1@sha256:2a90a6d26bd74eb8f2ad15c543cf5db85303dc822b74d613307a27fd2880adba
  - name: ghcr.io/nile-quran-community/nile-quran-django
    newTag: 1.4.6@sha256:d3e5c53fc10dc43dc566f0f7e32502be8d1029a41070a6f157b6bde8ec32f785
