apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./custom-resources/backend/pvc.yml
  - ./custom-resources/backend/configmap.yml
  - ./custom-resources/backend/sealed-secret.yml
  - ./custom-resources/backend/deployment.yml
  - ./custom-resources/backend/service.yml
  - ./custom-resources/frontend/configmap.yml
  - ./custom-resources/frontend/deployment.yml
  - ./custom-resources/frontend/service.yml
  - ./custom-resources/filters/rate-limit.yml
  - ./custom-resources/httproute/frontend.yml
  - ./custom-resources/ingress/nqc-backend.yml
images:
  - name: ghcr.io/nile-quran-community/nile-quran-nextjs
    newTag: 2.6.1@sha256:3edbe7ccb32f0ff7d41110efefaefdf431f451f16370596a84c27e633fb1b178
  - name: ghcr.io/nile-quran-community/nile-quran-django
    newTag: 1.2.0@sha256:079a784235780ba0e79fccaaa9df6e8b856028dd3fe3c5a0b9dfb79738458d69
