apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: tailscale
    name: tailscale-operator
    namespace: tailscale
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.102.2
    valuesFile: values.yml
resources:
  - ./custom-resources/sealed-secrets/oauth.yml
