# apiServerProxyConfig allows to configure whether the operator should expose
# Kubernetes API server.
# https://tailscale.com/kb/1437/kubernetes-operator-api-server-proxy
apiServerProxyConfig:
  # If true or noauth, the operator will run an in-process API server proxy.
  # You can deploy a ProxyGroup of type "kube-apiserver" to run a high
  # availability set of API server proxies instead.
  mode: "true"
  # Set to "true" to create the ClusterRole permissions required for the API
  # server proxy's auth mode. In auth mode, the API server proxy impersonates
  # groups and users based on tailnet ACL grants. Required for ProxyGroups of
  # type "kube-apiserver" running in auth mode.
  allowImpersonation: "true" # "true", "false"
