apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: traefik
    namespace: traefik
    name: traefik
    repo: https://traefik.github.io/charts
    version: 39.0.0
    valuesFile: values.yml
